name: sms
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.1
  contacts_service: ^0.4.6
  firebase_messaging: ^6.0.16
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  permission_handler: ^5.0.1
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Medium.ttf
          weight: 500
